skip_render: 
  # åªå¤„ç† _posts/publish/** æ–‡ä»¶, å…¶ä»–å…¨éƒ¨å¿½ç•¥
  - _posts/[0-9][0-9][0-9][0-9]/**
  # - _posts/publish/**

subtitle: å²æœˆé™å¥½ï¼Œè¯—é…’è¶å¹´åğŸº

exclude: 
  - images/**
  - js/**
  - css/**

neat_enable: true
# å‹ç¼© html
neat_html:
  enable: true
  exclude:
    - 'tags/**/index.html'
# å‹ç¼© css
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
# å‹ç¼© js
neat_js:
  enable: true
  mangle: true