skip_render: 
  # æ³¨é‡Šå³ä»£è¡¨æœ¬æ¬¡éœ€è¦å¤„ç†çš„ç›®å½•, å…¶ä»–çš„å…¨éƒ¨å¿½ç•¥
  - _posts/[0-9][0-9][0-9][0-9]/**
  - _posts/publish/**

subtitle: å²æœˆé™å¥½ï¼Œè¯—é…’è¶å¹´åğŸº
# æ˜¾ç¤ºè‰ç¨¿
render_drafts: true
# æœ¬åœ°å…³é—­åŠ å¯†
encrypt:
  enable: false

