skip_render: 
  # åªå¤„ç† _posts/publish/** æ–‡ä»¶, å…¶ä»–å…¨éƒ¨å¿½ç•¥
  - _posts/2012/**
  - _posts/2013/**
  - _posts/2014/**
  - _posts/2015/**
  - _posts/2016/**
  - _posts/2017/**
  - _posts/2018/**
  - _posts/2019/**
  - _posts/2020/**
  - _posts/2021/**
  - _posts/2022/**
  - _posts/2023/**
  - _posts/2024/**
  #- _posts/publish/**

subtitle: å²æœˆé™å¥½ï¼Œè¯—é…’è¶å¹´åğŸº

inject:
  head:
    # é¸¿è’™å­—ä½“
    - <link rel='stylesheet' href='https://s1.hdslb.com/bfs/static/jinkela/long/font/medium.css'>
    # https://blog.zhheo.com ç½‘ç«™çš„éƒ¨åˆ†æ ·å¼
    - <link rel="stylesheet" href="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/core.css">
    - <link rel="stylesheet" href="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/footer.css">
    # é¦–é¡µå›¾æ¸è¿›å¼åŠ è½½
    - <link rel="stylesheet" href="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/index-imgloaded.css">  
    # é¦–é¡µå›¾ç‰‡æ¸è¿›å¼åŠ è½½
    - <script src="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/index-imgloaded.js"></script> 
    - <script src="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/detect-devtools.js"></script> 
    # Umami è®¿é—®ç»Ÿè®¡
    - <script defer src="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/umami.self.js" data-website-id="bd4721b7-a43f-4161-83ed-51c148a7ca9d"></script>
  bottom:
    - <script src="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/dify/dify-chat.js"></script> 
    - <script src="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/dify/dify-chat.embed.min.js"></script> 
    # è®¢é˜…é¡µæ ·å¼
    - <link rel="stylesheet" href="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/subscribe.css" media="print" onload="this.media='all'">
    # é‚£å¹´ä»Šæ—¥å¡ç‰‡
    - <link rel="stylesheet" href="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/card-widget-today.css" media="print" onload="this.media='all'">
    # æ—¥å†å¡ç‰‡
    - <link rel="stylesheet" href="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/card-widget-calendar.css" media="print" onload="this.media='all'">
    # https://blog.meta-code.top/2024/10/27/2024-15/
    - <script async data-pjax src="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/automatic-redirection.js"></script>  
    # https://blog.zhheo.com/p/32a503a6.htmls
    - <script src="//geoip-js.com/js/apis/geoip2/v2.1/geoip2.js"></script>
    - <script src="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/geoip-check.js"></script>
    # æ¬¢è¿å¡ç‰‡
    - <script src="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/card-widget-welcome.js"></script>
    # æœ€æ–°è¯„è®º
    - <script async data-pjax src="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/card-widget-comments.js"></script>
    # é‚£å¹´ä»Šæ—¥å¡ç‰‡
    - <script async data-pjax src="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/card-widget-today.js"></script>
    # https://blog.bsgun.cn/posts/68c5cdb9/#2-%E6%B7%BB%E5%8A%A0%E7%BB%84%E4%BB%B6%E9%85%8D%E7%BD%AE
    - <script src="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/card-widget-countdown.js"></script>
    # æ—¥å†å¡ç‰‡
    - <script src="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/card-widget-calendar.js"></script>
    - <script async data-pjax src="https://open.lightxi.com/unpkg/chinese-lunar@0.1.4/lib/chinese-lunar.js"></script>
    # clipboard
    - <script async data-pjax src="https://cdn.bootcdn.net/ajax/libs/clipboard.js/2.0.11/clipboard.min.js"></script>
    # è‡ªå®šä¹‰js
    - <script src="https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/custom.js"></script>

githubcalendar:
  calendar_js: https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/github-calendar.js # æœ¬åœ°æ–‡ä»¶ï¼Œè¯·ä¸‹è½½åˆ°ä¸»é¢˜æ–‡ä»¶å¤¹çš„sourceç›®å½•ä¸‹

CDN:
  option:
    busuanzi: https://blog-1258270892.cos.ap-chengdu.myqcloud.com/source/static/busuanzi.self.js
